# Generated by Django 4.2.27 on 2025-12-25 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Keep announcements concise for mobile readability.')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('is_homepage_highlight', models.BooleanField(default=False, help_text='Check to display this prominently on the home page.')),
                ('is_published', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When should this announcement become visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-scheduled_at'],
            },
        ),
    ]
