# Generated by Django 4.2.27 on 2025-12-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_core', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('academic_levels', models.ManyToManyField(related_name='subjects', to='shop.academiclevel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
                'unique_together': {('name', 'is_core')},
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('book_type', models.CharField(choices=[('TEXTBOOK', 'Textbook'), ('WORKBOOK', 'Workbook'), ('PAST_QUESTIONS', 'Past Questions')], default='TEXTBOOK', max_length=20)),
                ('curriculum', models.CharField(choices=[('NACCA', 'NaCCA'), ('WAEC', 'WAEC')], default='NACCA', max_length=10)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='textbooks/covers/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title tag.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='textbooks', to='shop.academiclevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='textbooks', to='shop.subject')),
            ],
            options={
                'verbose_name': 'Textbook',
                'verbose_name_plural': 'Textbooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
